module Vaalit

  module Public
    SITE_ADDRESS        = ENV.fetch('SITE_ADDRESS')
    EMAIL_FROM_ADDRESS  = ENV.fetch('EMAIL_FROM_ADDRESS')
    EMAIL_FROM_NAME     = ENV.fetch('EMAIL_FROM_NAME')
    EXTERNAL_INFO_SITE  = ENV.fetch('EXTERNAL_INFO_SITE')
    EXTERNAL_INFO_PHONE = ENV.fetch('EXTERNAL_INFO_PHONE')
  end

  module Config
    VOTE_SIGNIN_STARTS_AT        = Time.parse ENV.fetch('VOTE_SIGNIN_STARTS_AT')
    VOTE_SIGNIN_ENDS_AT          = Time.parse ENV.fetch('VOTE_SIGNIN_ENDS_AT')
    ELIGIBILITY_SIGNIN_STARTS_AT = Time.parse ENV.fetch('ELIGIBILITY_SIGNIN_STARTS_AT')
    ELIGIBILITY_SIGNIN_ENDS_AT   = Time.parse ENV.fetch('ELIGIBILITY_SIGNIN_ENDS_AT')
    VOTING_GRACE_PERIOD_MINUTES  = ENV.fetch('VOTING_GRACE_PERIOD_MINUTES').to_i.minutes
    MAIL_BCC_ADDRESS             = ENV.fetch('MAIL_BCC_ADDRESS')
    SESSION_JWT_EXPIRY_MINUTES   = ENV.fetch('SESSION_JWT_EXPIRY_MINUTES').to_i.minutes
  end

  module Haka
    SAML_IDP_SSO_TARGET_URL             = ENV.fetch("SAML_IDP_SSO_TARGET_URL")
    SAML_IDP_ENTITY_ID                  = ENV.fetch("SAML_IDP_ENTITY_ID")
    SAML_ASSERTION_CONSUMER_SERVICE_URL = ENV.fetch("SAML_ASSERTION_CONSUMER_SERVICE_URL")
    SAML_ISSUER                         = ENV.fetch("SAML_ISSUER")
    SAML_IDP_CERT_FINGERPRINT           = ENV.fetch("SAML_IDP_CERT_FINGERPRINT")

    SAML_NAME_IDENTIFIER_FORMAT = "urn:oasis:names:tc:SAML:2.0:nameidformat:persistent"

    HAKA_STUDENT_NUMBER_FIELD   = ENV.fetch("HAKA_STUDENT_NUMBER_FIELD")
  end

end
